#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
killall -q polybar qv2ray picom
sleep 2; polybar example & qv2ray & picom &
fcitx5 &

vncserver &
nitrogen --restore
numlock &
xset r rate 200 30

xrandr --output DP1 --primary --mode 3840x2160 --pos 2160x0 --rotate normal --output DP2 --mode 1920x1080 --scale 2x2 --pos 0x0 --rotate left --output HDMI1 --off --output VIRTUAL1 --off
bspc monitor DP1 -d "  " "  " "  " "  " "  " "  " "  " "  " "  "
bspc monitor DP2 -d X
bspc monitor DP2 -s DP1


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# bspwm configuration
#bspc config top_padding             40
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"


# rules
bspc rule -a listen1 desktop=^8 follow=on state=floating
